package theclankers.tripview.ui.viewmodels

import kotlinx.serialization.builtins.serializer

// Use this ViewModel for a specific individual Trip.
// It will take as input a "trip_id" and return state variables defined in the ER diagram

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import theclankers.tripview.data.models.Stop
import java.io.BufferedReader
import java.io.InputStreamReader
import android.util.Log
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import theclankers.tripview.data.models.Trip
import theclankers.tripview.data.api.ApiClient
import theclankers.tripview.data.models.SuggestedStop
import theclankers.tripview.data.models.TripSuggestion
import kotlin.collections.filter

/**
 * ViewModel for managing data about a specific Trip.
 * Reads from a local LLM-generated JSON file (sample_response.txt).
 */
//class TripViewModel(application: Application) : AndroidViewModel(application) {
//
//    private val context = getApplication<Application>().applicationContext
//
//    private val _trips = MutableStateFlow<List<Trip>>(emptyList())
//    val trips: StateFlow<List<Trip>> = _trips
//
//    private val _stops = MutableStateFlow<List<Stop>>(emptyList())
//    val stops: StateFlow<List<Stop>> = _stops
//
//    private val _isLoading = MutableStateFlow(false)
//    val isLoading: StateFlow<Boolean> = _isLoading
//
//    private val _errorMessage = MutableStateFlow<String?>(null)
//    val errorMessage: StateFlow<String?> = _errorMessage
//
//    init {
//        loadTripDataFromFile("sample_genai_trip.txt")
//    }
//
//    /**
//     * Loads and parses the sample LLM JSON response from a .txt file in assets.
//     */
//    private fun loadTripDataFromFile(filename: String) {
//        viewModelScope.launch(Dispatchers.IO) {
//            _isLoading.value = true
//            try {
//                val inputStream = context.assets.open(filename)
//                val jsonString = BufferedReader(InputStreamReader(inputStream)).use { it.readText() }
//
//                val json = Json { ignoreUnknownKeys = true }
//                val parsedResponse = json.decodeFromString(LLMResponse.serializer(), jsonString)
//
//                // Convert parsed LLM trips to your Trip and Stop models
//                val convertedTrips = parsedResponse.trips.mapIndexed { index, trip ->
//                    Trip(
//                        tripId = index + 1,
//                        ownerId = 1, // Placeholder for now
//                        status = "Generated by LLM"
//                    )
//                }
//
//                val convertedStops = parsedResponse.trips.flatMapIndexed { tripIndex, trip ->
//                    trip.stops.mapIndexed { stopIndex, stop ->
//                        Stop(
//                            stopId = (tripIndex * 100) + stopIndex + 1,
//                            latitude = stop.coordinates.lat,
//                            longitude = stop.coordinates.lng,
//                            tripId = tripIndex + 1,
//                            description = stop.description,
//                            name = stop.name,
//                            order = stopIndex + 1,
//                            completed = false,
//                            stopType = stop.stopType
//                        )
//                    }
//                }
//
//                _trips.value = convertedTrips
//                _stops.value = convertedStops
//            } catch (e: Exception) {
//                _errorMessage.value = "Failed to parse JSON: ${e.message}"
//            } finally {
//                _isLoading.value = false
//            }
//        }
//    }
//
//    /**
//     * Helper: get stops for a specific tripId
//     */
//    fun getStopsForTrip(tripId: Int): List<Stop> {
//        return _stops.value.filter { it.tripId == tripId }
//    }
//}
//
//@Serializable
//data class LLMResponse(
//    val trips: List<LLMTrip>
//)
//
//@Serializable
//data class LLMTrip(
//    val destination: String,
//    @SerialName("duration_days") val durationDays: Int,
//    val version: Int,
//    val stops: List<LLMStop>
//)
//
//@Serializable
//data class LLMStop(
//    val coordinates: Coordinates,
//    val description: String,
//    val name: String,
//    @SerialName("stop_type") val stopType: String
//)
//
//@Serializable
//data class Coordinates(
//    val lat: Double,
//    val lng: Double
//)

class TripViewModel(private val token: String) : ViewModel() {
    val tripIdState: MutableState<Int?> = mutableStateOf(null)
    val ownerIdState: MutableState<Int?> = mutableStateOf(null)
    val statusState: MutableState<String?> = mutableStateOf(null)
    val drivingPolylineState: MutableState<String?> = mutableStateOf(null)
    val drivingPolylineTimestampState: MutableState<String?> = mutableStateOf(null)
    val nameState: MutableState<String?> = mutableStateOf(null)
    val descriptionState: MutableState<String?> = mutableStateOf(null)
    val stopIdsState: MutableState<List<Int>?> = mutableStateOf(null)
    // 🟣 List of invited friends for this trip
    val invitedFriendsState: MutableState<List<Int>> = mutableStateOf(emptyList())

    val isLoading: MutableState<Boolean> = mutableStateOf(false)
    val errorMessage: MutableState<String?> = mutableStateOf(null)
    val stops: MutableState<List<Stop>> = mutableStateOf(emptyList())



    fun loadTrip(tripId: Int) {
        viewModelScope.launch {
            isLoading.value = true
            errorMessage.value = null
            try {
                val trip = withContext(Dispatchers.IO) {
                    ApiClient.getTrip(token, tripId)
                }

                // ✅ Update each field from the loaded Trip
                tripIdState.value = trip.tripId
                ownerIdState.value = trip.ownerId
                statusState.value = trip.status
                drivingPolylineState.value = trip.drivingPolyline
                drivingPolylineTimestampState.value = trip.drivingPolylineTimestamp
                nameState.value = trip.name
                descriptionState.value = trip.description
                stopIdsState.value = trip.stopIds
                invitedFriendsState.value = trip.invitedFriends

                val stopResponse = withContext(Dispatchers.IO) {
                    ApiClient.getTripStops(token, tripId)
                }
                val stopjson = JSONArray(stopResponse)
                val s = mutableListOf<Stop>()

                for (i in 0 until stopjson.length()) {
                    val stopObject = stopjson.getJSONObject(i)
                    s.add(
                        Stop(
                            stopId = stopObject.getInt("stop_id"),
                            latitude = stopObject.getDouble("latitude"),
                            longitude = stopObject.getDouble("longitude"),
                            order = stopObject.getInt("order"),
                            completed = stopObject.getBoolean("completed"),
                            stopType = stopObject.getString("stop_type"),
                            name = stopObject.getString("name"),
                            tripId = tripId
                        )
                    )
                }

                stops.value = s

                Log.d("TripViewModel", "✅ Trip loaded: ${trip.name}")

            } catch (e: Exception) {
                Log.e("TripViewModel", "❌ Failed to load trip", e)
                errorMessage.value = e.message
            } finally {
                isLoading.value = false
            }
        }
    }

    fun updateTrip(tripId: Int, stops: List<Stop>) {
        viewModelScope.launch {
            try {
                // 🔹 Send the update to the backend
                withContext(Dispatchers.IO) {
                    ApiClient.updateStops(token, tripId, stops)
                }


                Log.d("TripViewModel", "✅ Stops updated  ")
            } catch (e: Exception) {
                Log.e("TripViewModel", "❌ Failed to update stops", e)
                e.printStackTrace()
            }
        }
    }

    fun archiveTrip(tripId: Int) {
        viewModelScope.launch {
            try {
                // 🔹 Send the update to the backend
                withContext(Dispatchers.IO) {
                    ApiClient.archiveTrip(token, tripId)
                }


                Log.d("TripViewModel", "✅ Trip archived ")
            } catch (e: Exception) {
                Log.e("TripViewModel", "❌ Failed to archive trip", e)
                e.printStackTrace()
            }
        }
    }

    fun deleteStop(stopId: Int) {

        stops.value = stops.value.filter { it.stopId != stopId }
        stopIdsState.value = stopIdsState.value?.filter { it != stopId }

        viewModelScope.launch {
            try {
                // 🔹 Send the update to the backend
                withContext(Dispatchers.IO) {
                    ApiClient.deleteStop(token, stopId)
                }

                Log.d("TripViewModel", "✅ Stop deleted ")
            } catch (e: Exception) {
                Log.e("TripViewModel", "❌ Failed to delete stop", e)
                e.printStackTrace()
            }
        }
    }
    val isAddingStopState: MutableState<Boolean> = mutableStateOf(false)
    val addStopMessageState: MutableState<String?> = mutableStateOf(null)

    fun addStop(tripId: Int, name: String, latitude: String, longitude: String) {
        viewModelScope.launch {
            isAddingStopState.value = true
            try {
                ApiClient.addStop(token, tripId, name, latitude, longitude)
                addStopMessageState.value = "Successfully added stop"
            } catch (e: Exception) {
                Log.e("TripViewModel", "❌ Failed to add stop", e)
                addStopMessageState.value = "Failed to add stop"
                e.printStackTrace()
            } finally {
                isAddingStopState.value = false
            }
        }
    }

    fun inviteFriend(tripId: Int, friendId: Int, onComplete: () -> Unit) {
        viewModelScope.launch {
            try {
                withContext(Dispatchers.IO) {
                    ApiClient.inviteFriend(token, tripId, friendId)
                }

                // Update UI list
                val updated = invitedFriendsState.value.toMutableList()
                if (!updated.contains(friendId)) updated.add(friendId)
                invitedFriendsState.value = updated

            } catch (e: Exception) {
                Log.e("TripViewModel", "❌ Failed to invite friend $friendId", e)
            } finally {
                onComplete()
            }
        }
    }

    fun uninviteFriend(tripId: Int, friendId: Int, onComplete: () -> Unit) {
        viewModelScope.launch {
            try {
                withContext(Dispatchers.IO) {
                    ApiClient.uninviteFriend(token, tripId, friendId)
                }

                // Update UI list
                invitedFriendsState.value =
                    invitedFriendsState.value.filter { it != friendId }

            } catch (e: Exception) {
                Log.e("TripViewModel", "❌ Failed to uninvite friend $friendId", e)
            } finally {
                onComplete()
            }
        }
    }

}


@Composable
fun useTrip(token: String, tripId: Int): TripViewModel {
    val viewModel = remember { TripViewModel(token) }

    LaunchedEffect(tripId) {
        viewModel.loadTrip(tripId)
    }

    return viewModel
}

fun TripSuggestion.toTrip(ownerId: Int = -1): Trip {
    return Trip(
        tripId = -1, // LLM suggestions don't have real IDs yet
        ownerId = ownerId,
        status = "suggested",
        drivingPolyline = "",
        drivingPolylineTimestamp = "",
        name = this.name,
        description = this.description,
        stopIds = this.stops.map { it.order }, // temporary
        invitedFriends = emptyList()
    )
}


fun SuggestedStop.toStop(tempTripId: Int = -1): Stop {
    return Stop(
        stopId = -1, // not real yet
        latitude = this.latitude,
        longitude = this.longitude,
        order = this.order,
        completed = false,
        stopType = this.stopType,
        name = this.name,
        tripId = tempTripId
    )
}

fun parseTripSuggestions(json: JSONArray): List<TripSuggestion> {
    val list = mutableListOf<TripSuggestion>()


    for (i in 0 until json.length()) {
        val obj = json.getJSONObject(i)
        val stopsJSONArray = obj.getJSONArray("stops") //this might cause problems tbh
        val stopsJson = obj.getJSONArray("stops")
        val stops = mutableListOf<SuggestedStop>()

        for (j in 0 until stopsJson.length()) {
            val stopObj = stopsJson.getJSONObject(j)
            stops.add(
                SuggestedStop(
                    name = stopObj.getString("name"),
                    description = stopObj.getString("description"),
                    latitude = stopObj.getDouble("latitude"),
                    longitude = stopObj.getDouble("longitude"),
                    order = stopObj.getInt("order"),
                    stopType = stopObj.getString("stop_type")
                )
            )
        }

        list.add(
            TripSuggestion(
                name = obj.getString("name"),
                description = obj.getString("description"),
                totalCostEstimate = obj.getInt("total_cost_estimate"),
                costBreakdown = obj.getString("cost_breakdown"),
                transportationSummary = obj.getString("transportation_summary"),
                transportationBreakdown = obj.getString("transportation_breakdown"),
                stops = stops,
                version = obj.getInt("version") ,
                stopsJSONArray = stopsJSONArray // <-- pass it here
            )
        )
    }

    return list
}

val tripSuggestions: MutableState<List<Trip>> = mutableStateOf(emptyList())


