package theclankers.tripview.ui.viewmodels

import kotlinx.serialization.builtins.serializer

// Use this ViewModel for a specific individual Trip.
// It will take as input a "trip_id" and return state variables defined in the ER diagram

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import theclankers.tripview.data.models.Stop
import java.io.BufferedReader
import java.io.InputStreamReader
import android.util.Log
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.launch
import theclankers.tripview.data.models.Trip
import theclankers.tripview.data.api.ApiClient

/**
 * ViewModel for managing data about a specific Trip.
 * Reads from a local LLM-generated JSON file (sample_response.txt).
 */
class TripViewModel(application: Application) : AndroidViewModel(application) {

    private val context = getApplication<Application>().applicationContext

    private val _trips = MutableStateFlow<List<Trip>>(emptyList())
    val trips: StateFlow<List<Trip>> = _trips

    private val _stops = MutableStateFlow<List<Stop>>(emptyList())
    val stops: StateFlow<List<Stop>> = _stops

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading

    private val _errorMessage = MutableStateFlow<String?>(null)
    val errorMessage: StateFlow<String?> = _errorMessage

    init {
        loadTripDataFromFile("sample_genai_trip.txt")
    }

    /**
     * Loads and parses the sample LLM JSON response from a .txt file in assets.
     */
    private fun loadTripDataFromFile(filename: String) {
        viewModelScope.launch(Dispatchers.IO) {
            _isLoading.value = true
            try {
                val inputStream = context.assets.open(filename)
                val jsonString = BufferedReader(InputStreamReader(inputStream)).use { it.readText() }

                val json = Json { ignoreUnknownKeys = true }
                val parsedResponse = json.decodeFromString(LLMResponse.serializer(), jsonString)

                // Convert parsed LLM trips to your Trip and Stop models
                val convertedTrips = parsedResponse.trips.mapIndexed { index, trip ->
                    Trip(
                        tripId = index + 1,
                        ownerId = 1, // Placeholder for now
                        status = "Generated by LLM"
                    )
                }

                val convertedStops = parsedResponse.trips.flatMapIndexed { tripIndex, trip ->
                    trip.stops.mapIndexed { stopIndex, stop ->
                        Stop(
                            stopId = (tripIndex * 100) + stopIndex + 1,
                            latitude = stop.coordinates.lat,
                            longitude = stop.coordinates.lng,
                            tripId = tripIndex + 1,
                            description = stop.description,
                            name = stop.name,
                            order = stopIndex + 1,
                            completed = false,
                            stopType = stop.stopType
                        )
                    }
                }

                _trips.value = convertedTrips
                _stops.value = convertedStops
            } catch (e: Exception) {
                _errorMessage.value = "Failed to parse JSON: ${e.message}"
            } finally {
                _isLoading.value = false
            }
        }
    }

    /**
     * Helper: get stops for a specific tripId
     */
    fun getStopsForTrip(tripId: Int): List<Stop> {
        return _stops.value.filter { it.tripId == tripId }
    }
}

@Serializable
data class LLMResponse(
    val trips: List<LLMTrip>
)

@Serializable
data class LLMTrip(
    val destination: String,
    @SerialName("duration_days") val durationDays: Int,
    val version: Int,
    val stops: List<LLMStop>
)

@Serializable
data class LLMStop(
    val coordinates: Coordinates,
    val description: String,
    val name: String,
    @SerialName("stop_type") val stopType: String
)

@Serializable
data class Coordinates(
    val lat: Double,
    val lng: Double
)
class TripViewModel(private val token: String) : ViewModel() {
    val tripIdState: MutableState<Int?> = mutableStateOf(null)
    val ownerIdState: MutableState<Int?> = mutableStateOf(null)
    val statusState: MutableState<String?> = mutableStateOf(null)
    val drivingPolylineState: MutableState<String?> = mutableStateOf(null)
    val drivingPolylineTimestampState: MutableState<String?> = mutableStateOf(null)
    val nameState: MutableState<String?> = mutableStateOf(null)
    val descriptionState: MutableState<String?> = mutableStateOf(null)
    val stopIdsState: MutableState<List<Int>?> = mutableStateOf(null)
    val isLoading: MutableState<Boolean> = mutableStateOf(false)
    val errorMessage: MutableState<String?> = mutableStateOf(null)

    fun loadTrip(tripId: Int) {
        viewModelScope.launch {
            isLoading.value = true
            errorMessage.value = null
            try {
                val trip = ApiClient.getTrip(token, tripId)

                // ✅ Update each field from the loaded Trip
                tripIdState.value = trip.tripId
                ownerIdState.value = trip.ownerId
                statusState.value = trip.status
                drivingPolylineState.value = trip.drivingPolyline
                drivingPolylineTimestampState.value = trip.drivingPolylineTimestamp
                nameState.value = trip.name
                descriptionState.value = trip.description
                stopIdsState.value = trip.stopIds

                Log.d("TripViewModel", "✅ Trip loaded: ${trip.name}")

            } catch (e: Exception) {
                Log.e("TripViewModel", "❌ Failed to load trip", e)
                errorMessage.value = e.message
            } finally {
                isLoading.value = false
            }
        }
    }
}


@Composable
fun useTrip(token: String, tripId: Int): TripViewModel {
    val viewModel = remember { TripViewModel(token) }

    LaunchedEffect(tripId) {
        viewModel.loadTrip(tripId)
    }

    return viewModel
}
